commands:
docker run <namecontainer> /*(Create container)*/
docker ps /*(shows active containers)*/
docker ps -a /*(shows all containers)*/
docker inspect <containe ID> /*(shows a container detail with id container)*/
docker inspect <containername> /*(shows a container detail with name container)*/
docker run –-name <containername> <containernickname> /*(Is assined a custom nickname “hello-platzi”)*/
docker rename hello-platzi hola-platzy /*(rename a container)*/
docker rm <ID o nombre> /*(drop a container)*/
docker container prune /*(Delete all the containers in stop)*/

//bind mounts - transfer data to the administrator
$docker run  -d --name mongodb -v rutaAdministrador:rutacontenedor mongo /*(All in this path in the container will be saved out the container in the principal machine)*/

//docker volumes
docker volume ls /*(shows all volumes)*/
docker volume create <volumename> /*(create a volume)*/
docker run -d --name db --mount src=<volumename>,dst=/data/db mongo /*(create db and execute volume)*/

//networks
$ docker network ls /*(shows all networks)*/
$ docker network inspect <networkname> /*(shows all the network details)*/
  
//docker compose
$ docker-compose logs /*(shows all the logs)*/
$ docker-compose logs app /*(shows the “app” logs)*/
$ docker-compose logs -f app /*(shows and follow the "app" logs)*/
$ docker-compose exec app bash /*(goes inside the container app shell)*/
$ docker-compose ps /*(shows all the containers generated by docker-compose)*/
$ docker-compose down /*(delete all that was generated by docker-compose)	*/

$ docker-compose build /*(creates images)*/
$ docker-compose up -d /*(creates services/containers)*/
